version: "3.3"

services:
  nginx:
    build:
      context: .
      dockerfile: deployment/local/docker/nginx/Dockerfile
    ports:
      - "${DOCKER_NGINX_PORT}:80"
    links:
      - php-fpm
    volumes:
      - ./:/var/www
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: .
      dockerfile: deployment/local/docker/php-fpm/Dockerfile
    volumes:
      - ./:/var/www
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis
    container_name: mailer_k8s_api_php_fpm
  mysql:
    build:
      context: .
      dockerfile: deployment/local/docker/mysql/Dockerfile
    ports:
      - "${DOCKER_MYSQL_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mailer
    volumes:
      - ./persistent_data/mysql:/var/lib/mysql
  redis:
    build:
      context: .
      dockerfile: deployment/local/docker/redis/Dockerfile
    ports:
      - "${REDIS_PORT}:6379"
  queue-worker:
    build:
      context: .
      dockerfile: deployment/local/docker/queue-worker/Dockerfile
    volumes:
      - ./:/var/www
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis
    container_name: mailer_k8s_api_queue_worker
