apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: mailer-app
    namespace: default
    labels:
        app: mailer-app
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mailer-php-fpm
    template:
        metadata:
            labels:
                app: mailer-php-fpm
                #trier: backend
        spec:
            containers:
                - name: mailer-web
                  image: mailer-k8s:1.0
                  #imagePullPolicy: Never
                  ports:
                      - containerPort: 9000
                        protocol: TCP
                  env:
                      - name: "APP_KEY"
                        valueFrom:
                            secretKeyRef:
                                name: mailer-app-secret
                                key: app_key
                      - name: "DB_DATABASE"
                        valueFrom:
                            secretKeyRef:
                                name: mailer-mysql-secret
                                key: db_name
                      - name: "DB_USERNAME"
                        valueFrom:
                            secretKeyRef:
                                name: mailer-mysql-secret
                                key: db_username
                      - name: "DB_USERNAME"
                        valueFrom:
                            secretKeyRef:
                                name: mailer-mysql-secret
                                key: db_password
                  envFrom:
                      - configMapRef:
                            name: redis-config
