apiVersion: v1
kind: Service
metadata:
    name: mailer-mysql-service-external
    #labels:
        #app: wordpress
spec:
    type: NodePort
    ports:
        - port: 3306
          targetPort: 3306
          nodePort: 31306
    selector:
        app: mailer-mysql
        tier: mysql
