apiVersion: v1
kind: Service
metadata:
    name: mailer-mysql-service
spec:
    ports:
        - port: 3306
    selector:
        app: mailer-mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: mailer-mysql
    labels:
        app: mailer-mysql
spec:
    selector:
        matchLabels:
            app: mailer-mysql
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                app: mailer-mysql
                tier: mysql
        spec:
            containers:
            - name: mailer-mysql
              image: mysql:5.7
              imagePullPolicy: IfNotPresent
              env:
              - name: MYSQL_ROOT_PASSWORD
                #value: password
                valueFrom:
                  secretKeyRef:
                    name: mailer-mysql-secret
                    key: db_password
              - name: MYSQL_DATABASE
                #value: mailer
                valueFrom:
                  secretKeyRef:
                    name: mailer-mysql-secret
                    key: db_name
              ports:
              - containerPort: 3306
                protocol: TCP
              volumeMounts:
              - name: mysql-persistent-storage
                mountPath: /var/lib/mysql
            volumes:
            - name: mysql-persistent-storage
              persistentVolumeClaim:
                claimName: mysql-pv-claim
