apiVersion: v1
kind: Service
metadata:
    name: nginx-service
        #labels:
    #app: wordpress
spec:
    type: NodePort
    ports:
        - port: 80
          targetPort: 80
          nodePort: 31080
    selector:
        app: nginx
